apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer-1
  namespace: dev
spec:
  type: LoadBalancer
  loadBalancerIP: 172.25.230.19
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginxserver

