apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    app: uber
    tier: backend
    env: staging
    backup: weekly
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80

