apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    name: liveness
spec:
  containers:
    - name: liveness
      image: quay.io/gauravkumar9130/jenkins
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command: ["ls","/usr/share/jenkins/jenkins.war"]
        initialDelaySeconds: 5
        periodSeconds: 5
