apiVersion: v1             
kind: Pod                  
metadata:                  
  name: black-pod          
  labels:                  
    color: black           
spec:                      
  containers:              
  - name: cont1            
    image: quay.io/shruti1988/webapp
    securityContext:       
      capabilities:        
        add: [ "NET_RAW" ]
