apiVersion: v1
kind: Pod
metadata: 
  name: affinity-thing
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  containers:
  - name: abc
    image: quay.io/shruti1988/webapp
