apiVersion: v1
kind: Pod
metadata: 
  name: plainkey-pod
spec:
  containers:
  - name: xyz
    image: quay.io/anshuk6469/mysql
    env:
    - name: MYSQL_USER
      value: tony
    - name: MYSQL_ROOT_PASSWORD
      value: redhat
    - name: MYSQL_PASSWORD
      value: redhat
    - name: MYSQL_DATABASE
      value: cka-hello
