apiVersion: v1
kind: Pod
metadata:
  name: cka-training-pod
spec:
  containers:
  - name: xyz
    image: quay.io/shruti1988/webapp
    volumeMounts:
    - name: koenig
      mountPath: /usr/share/nginx/html
  volumes:
  - name: koenig
    configMap:
      name: myconfig
