apiVersion: v1
kind: Pod
metadata: 
  name: secret-pod
spec:
  containers:
  - name: xyz
    image: quay.io/anshuk6469/mysql
    imagePullPolicy: IfNotPresent
    envFrom:
    - secretRef:
        name: mysecret
